### ISSUE TITLE
Update music tracks in 2020 ?

### ISSUE THREAD

**Issue by robbiedood** [David-Jackson/YouTubeAudioLibraryAPI#1]
Dear David-Jackson,

Thanks for the git work. It is very useful.

I was wondering if you have a plan to update youtube_music_library.json in order to include latest music / soundeffects in 2020 ?

Thank you !

**Comment by David-Jackson** [comment]
Absolutely! It would be a good idea to update this regularly. Updated with 019067ea916204191fe3ca0df343466863fcf570.

**Comment by lukelu520** [comment]
David-Jackson, Thank you for your prompt update !!
